export const propertiesData = [
  {
    id: 'buy-1',
    name: 'Palm Harbor',
    price: '2,095',
    type: 'house',
    location: 'New York',
    address: '2699 Green Valley, NY',
    beds: 3,
    bathrooms: 2,
    area: '2,400 sqft',
    isPopular: true,
    image: '/home/heroSection/screen-shot-2025-04-29-at-9.12.16-am_m.webp',
  },
  {
    id: 'buy-2',
    name: 'Beverly Suites',
    price: '4,500',
    type: 'apartment',
    location: 'Los Angeles',
    address: '90210 Wilshire Blvd, LA',
    beds: 2,
    bathrooms: 2,
    area: '1,800 sqft',
    isPopular: false,
    image: '/home/heroSection/7535-front-photo_m.webp',
  },
  {
    id: 'buy-3',
    name: 'Faulkner Ave',
    price: '1,200',
    type: 'house',
    location: 'Chicago',
    address: '4528 Faulkner Ave, IL',
    beds: 4,
    bathrooms: 3,
    area: '3,100 sqft',
    isPopular: false,
    image: '/home/heroSection/dji_0481_1_m.webp',
  },
  {
    id: 'buy-4',
    name: 'St. Andrew Cottage',
    price: '2,400',
    type: 'house',
    location: 'New York',
    address: '789 St. Andrew Rd, NY',
    beds: 3,
    bathrooms: 3,
    area: '2,200 sqft',
    isPopular: true,
    image: '/home/heroSection/istockphoto-968025444-612x612.jpg',
  },
  {
    id: 'buy-5',
    name: 'The Grand Skyline',
    price: '6,000',
    type: 'apartment',
    location: 'Los Angeles',
    address: '101 Sunset Blvd, LA',
    beds: 3,
    bathrooms: 4,
    area: '4,200 sqft',
    isPopular: false,
    image: '/home/heroSection/lg130-front-gpt_m.webp',
  },
  {
    id: 'buy-6',
    name: 'Woodland Retreat',
    price: '1,850',
    type: 'house',
    location: 'Chicago',
    address: '882 Timberline Dr, IL',
    beds: 2,
    bathrooms: 2,
    area: '1,500 sqft',
    isPopular: false,
    image: '/home/heroSection/main-rendering-edit_55_m.webp',
  },
  {
    id: 'buy-7',
    name: 'Luxury Villa',
    price: '3,500',
    type: 'house',
    location: 'Malibu',
    address: '123 Malibu Rd, CA',
    beds: 5,
    bathrooms: 4,
    area: '3,500 sqft',
    isPopular: true,
    image: '/home/heroSection/istockphoto-1214971896-612x612.jpg',
  },
  {
    id: 'buy-8',
    name: 'Modern Loft',
    price: '2,800',
    type: 'apartment',
    location: 'New York',
    address: '55 Broadway, NY',
    beds: 2,
    bathrooms: 2,
    area: '1,600 sqft',
    isPopular: false,
    image: '/home/heroSection/istockphoto-1364477107-612x612.jpg',
  },
  {
    id: 'buy-9',
    name: 'Garden House',
    price: '2,100',
    type: 'house',
    location: 'Austin',
    address: '789 Maple Ave, TX',
    beds: 3,
    bathrooms: 2,
    area: '2,000 sqft',
    isPopular: false,
    image: '/home/heroSection/Gemini_Generated_Image_2v44me2v44me2v44.png',
  },
  {
    id: 'buy-10',
    name: 'Skyline Penthouse',
    price: '5,500',
    type: 'apartment',
    location: 'New York',
    address: '101 High Rise, NY',
    beds: 4,
    bathrooms: 4,
    area: '4,000 sqft',
    isPopular: true,
    image: '/home/heroSection/main-rendering-edit-37_m.webp',
  },
  {
    id: 'buy-11',
    name: 'Cozy Cottage',
    price: '1,900',
    type: 'house',
    location: 'Portland',
    address: '222 Forest Path, OR',
    beds: 2,
    bathrooms: 1,
    area: '1,400 sqft',
    isPopular: false,
    image: '/home/heroSection/istockphoto-519434778-612x612.jpg',
  },
  {
    id: 'buy-12',
    name: 'Riverside Home',
    price: '2,300',
    type: 'house',
    location: 'Denver',
    address: '333 River Rd, CO',
    beds: 3,
    bathrooms: 2,
    area: '2,100 sqft',
    isPopular: false,
    image: '/home/heroSection/lg130-front-gpt_m.webp',
  },
];